name: Build and Publish to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - 'memolog/**'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vault repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clone publish repository
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: |
          git clone https://${PUBLISH_TOKEN}@github.com/xcd0/public-memo.git publish-repo
          cd publish-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Quartz in publish repository
        working-directory: publish-repo
        run: |
          # Quartzがセットアップ済みかチェック。
          if [ ! -f "package.json" ] || ! grep -q "quartz" package.json; then
            echo "Quartz is not setup. Setting up now..."

            # Quartzの初期化（デフォルト設定を使用）。
            npm install -g @jackyzha0/quartz
            npx quartz create --strategy=empty

            echo "Quartz setup completed!"
            git add .
            git commit -m "feat: Auto-setup Quartz" || echo "No changes to commit"
          else
            echo "Quartz is already setup."
          fi

      - name: Clear and copy Markdown files to content directory
        run: |
          # content/ディレクトリをクリア（.gitは保持）。
          find publish-repo/content -mindepth 1 ! -path '*/\.git/*' -delete 2>/dev/null || true

          # 公開対象ディレクトリのMarkdownファイルをコピー。
          mkdir -p publish-repo/content
          if [ -d "memolog" ]; then
            cp -r memolog/* publish-repo/content/ || true
          fi

          # ファイル数を確認。
          file_count=$(find publish-repo/content -name "*.md" | wc -l)
          echo "Copied $file_count Markdown files"

      - name: Build Quartz
        working-directory: publish-repo
        run: |
          # Node modules がない場合はインストール。
          if [ ! -d "node_modules" ]; then
            npm install
          fi

          # Quartzでビルド。
          npm run build

          echo "Quartz build completed!"
          ls -la public/

      - name: Push built site to publish repository
        working-directory: publish-repo
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: |
          git add .

          # 変更があればコミット。
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: Update published site ($(date -u +%Y-%m-%d %H:%M:%S))"
            git push https://${PUBLISH_TOKEN}@github.com/xcd0/public-memo.git main
            echo "Changes pushed to publish repository"
          fi
