name: Sync Markdown to Quartz Repository

on:
  push:
    branches: [main, master]
    paths:
      - 'memolog/**'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vault repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Quartz repository
        uses: actions/checkout@v4
        with:
          repository: xcd0/public-memo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: quartz-repo

      - name: Setup Node.js
        if: true == true
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Auto-setup Quartz (if not already setup)
        if: true == true
        working-directory: quartz-repo
        env:
          QUARTZ_CONFIG: '{
  "siteTitle": "My Published Notes",
  "locale": "ja-JP",
  "enableSPA": true,
  "enablePopovers": true,
  "baseUrl": "xcd0.github.io/public-memo",
  "typography": {
    "header": "Schibsted Grotesk",
    "body": "Source Sans Pro",
    "code": "IBM Plex Mono"
  },
  "colors": {
    "lightMode": {
      "light": "#faf8f8",
      "lightgray": "#e5e5e5",
      "gray": "#b8b8b8",
      "darkgray": "#4e4e4e",
      "dark": "#2b2b2b",
      "secondary": "#284b63",
      "tertiary": "#84a59d",
      "highlight": "rgba(143, 159, 169, 0.15)"
    },
    "darkMode": {
      "light": "#161618",
      "lightgray": "#393639",
      "gray": "#646464",
      "darkgray": "#d4d4d4",
      "dark": "#ebebec",
      "secondary": "#7b97aa",
      "tertiary": "#84a59d",
      "highlight": "rgba(143, 159, 169, 0.15)"
    }
  }
}'
        run: |
          # Quartzがセットアップ済みかチェック。
          if [ ! -f "package.json" ] || ! grep -q "quartz" package.json; then
            echo "Quartz is not setup. Setting up now..."

            # package.jsonを作成。
            cat > package.json << 'EOF'
{
  "name": "@jackyzha0/quartz",
  "description": "Quartz - a fast, batteries-included static-site generator",
  "version": "4.0.0",
  "type": "module",
  "author": "jackyzha0 <j.zhao2k19@gmail.com>",
  "license": "MIT",
  "homepage": "https://quartz.jzhao.xyz",
  "repository": {
    "type": "git",
    "url": "https://github.com/jackyzha0/quartz.git"
  },
  "scripts": {
    "build": "npx quartz build",
    "serve": "npx quartz build --serve"
  },
  "dependencies": {
    "@jackyzha0/quartz": "^4.0.0"
  }
}
EOF

            # Quartzをインストール。
            npm install

            # quartz.config.tsを生成。
            npx quartz create --strategy=empty

            # 設定ファイルを上書き。
            cat > quartz.config.ts << 'EOFCONFIG'
import { QuartzConfig } from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

const config = $QUARTZ_CONFIG

const quartzConfig: QuartzConfig = {
  configuration: {
    pageTitle: config.siteTitle,
    enableSPA: config.enableSPA,
    enablePopovers: config.enablePopovers,
    analytics: {
      provider: "plausible",
    },
    locale: config.locale,
    baseUrl: config.baseUrl,
    ignorePatterns: ["private", "templates", ".obsidian"],
    defaultDateType: "created",
    theme: {
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: config.typography,
      colors: config.colors,
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({
        priority: ["frontmatter", "filesystem"],
      }),
      Plugin.SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      Plugin.ObsidianFlavoredMarkdown({ enableInHtmlEmbed: false }),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({ markdownLinkResolution: "shortest" }),
      Plugin.Description(),
      Plugin.Latex({ renderEngine: "katex" }),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
      }),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.NotFoundPage(),
    ],
  },
}

export default quartzConfig
EOFCONFIG

            # deploy.ymlを生成。
            mkdir -p .github/workflows
            cat > .github/workflows/deploy.yml << 'EOFDEPLOY'
name: Build and Deploy Quartz

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
EOFDEPLOY

            git add .
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "feat: Auto-setup Quartz" || echo "No changes to commit"
            git push

            echo "Quartz setup completed!"
          else
            echo "Quartz is already setup."
          fi

      - name: Copy Markdown files to Quartz content directory
        run: |
          # 公開用リポジトリのcontent/ディレクトリをクリア（.gitは保持）。
          find quartz-repo/content -mindepth 1 ! -path '*/\.git/*' -delete 2>/dev/null || true

          # 公開対象ディレクトリのMarkdownファイルをコピー。
          mkdir -p quartz-repo/content
          if [ -d "memolog" ]; then
            cp -r memolog/* quartz-repo/content/ || true
          fi

          # ファイル数を確認。
          file_count=$(find quartz-repo/content -name "*.md" | wc -l)
          echo "Copied $file_count Markdown files"

      - name: Commit and push content to Quartz repository
        working-directory: quartz-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add content/

          # 変更があればコミット。
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: Sync content from vault ($(date -u +%Y-%m-%d %H:%M:%S))"
            git push
            echo "Changes pushed to Quartz repository"
          fi
